### ISSUE TITLE
Drones manager has not been tested in the real world

### ISSUE THREAD

**Issue by ennuuos** [ennuuos/DronesDoingDroneThingsThreePointOh#1]
The Drones class has not been confirmed to work with an actual drone, in fact it hasn't even been run at all.

I need someone (looking at you @thewrongjames) to test it by creating a new drone instance with an interval event that flashes the lights or something.

#### Test Requirements
 - Drone connects to server (lights should flash)
 - Drone receives command (lights should flash)
 - Drone accepts commands after disconnecting and reconnecting (use ```setInterval``` to send it repeated commands)

**Comment by ennuuos** [comment]
I will upload a snippet of code that lets you test the stuff if I can be bothered later tonight / early tomorrow

**Comment by thewrongjames** [comment]
Don't worry, I expect I can work it out.

**Comment by thewrongjames** [comment]
Upon first connect the drones lights do flash, and the server begins logging navdata, however, if the drone is turned off, the lights do not flash.

The server seems to occasionally start logging navdata after some time, but that seemed to usually not contain the demo data (more checks on everything in this sentence are needed).

The first line of the `Drones.add` method (`if (this.containsId(id)) return this.getDrone(id)`) certainly contributes to this, as if the server already thinks the drone exists it will do nothing, but removing this, or ensuring that the server's ar-drone object for the drone does not exist before reconnection (by, for instance routing a http delete method to point to `Drones.remove`) does not result in the drone reconnecting as desired.

This issue still needs to be investigated further.

**Comment by thewrongjames** [comment]
I have realised I am actually not sure what you (@ennuuos) meant by 'drone accepts commands', I do not see a route or method for sending commands to the drones. Additionally, as mentioned in [this issue](https://github.com/ennuuos/DronesDoingDroneThingsThreePointOh/issues/9), and in my previous message, reconnection does not work, and I will be attempting to address that over there.

As mentioned in my previous comment, the lights do flash upon connection, so, that just leaves the two things above to do, so, I await your (@ennuuos) response on the first one, and I will work on the second over on the relevant issue.

**Comment by thewrongjames** [comment]
As stated [here](https://github.com/ennuuos/DronesDoingDroneThingsThreePointOh/issues/9), the reconnection issue has been fixed, and the lights do flash upon connection and reconnection, which I believe covers all your requirements (as there is no route for commands yet, but connecting essentially sends one), as such, I shall mark this as closed.
