### ISSUE TITLE
Add client command routes

### ISSUE THREAD

**Issue by thewrongjames** [ennuuos/DronesDoingDroneThingsThreePointOh#10]
There is currently no system for sending commands to the drones. At all. One of the first steps to setting one up is having the server side routes to map urls and data posted to urls to drone commands. This needs to be done.

**Comment by ennuuos** [comment]
I think it would be wise to use JSON and transmit to a single URL which will decrease network traffic.

The server can parse the JSON easily anyway.

This would be in the same format as the status packets i.e a list of objects with IDs

**Comment by thewrongjames** [comment]
Yes, I agree, and I have done it that way. They pass in an array of objects containing 'id's, 'commandName's, and optionally 'degree's, and these are then acted on.
