### ISSUE TITLE
Is the ping module required?

### ISSUE THREAD

**Issue by thewrongjames** [ennuuos/DronesDoingDroneThingsThreePointOh#12]
Currently our project requires the ping module, but I don't believe it is used anywhere inside the project, and now that the connection issue has been fixed, I am not sure there is even an apparent need for it in future parts of the project. If someone could confirm this (possible just me in the future), we can remove it from our list of dependancies.

**Comment by thewrongjames** [comment]
It was involved in a possible solution to #6, but, as mentioned there, that was fixed using a timeout on navdata.

**Comment by ennuuos** [comment]
As far as I know it is unnecessary. At some point we should get around to removing it
