### ISSUE TITLE
Drones.remove(id) does not remove drones

### ISSUE THREAD

**Issue by thewrongjames** [ennuuos/DronesDoingDroneThingsThreePointOh#23]
This seems to possibly be something about how arrays and the delete keyword work in Javascript, but the result is that remove does not actually remove.

I only noticed this because I was fixing up the tests for the Drones class (see #21), and I couldn't work out why one of the expects on remove was failing, and it was because remove was actually faliing its test. Here is some example Javascript to actually explain what is happening.

```js
> const array = [{id: 0}, {id: 1}, {id: 2}]
// Returns undefined.
> array
// Returns [ { id: 0 }, { id: 1 }, { id: 2 } ]
> array.find(item => item.id = 1)
// Returns { id: 1}
> delete array.find(item => item.id = 1)
// Returns true
> array
// Returns [ { id: 0 }, { id: 1 }, { id: 2 } ]
```

So, as you can see delete doesn't remove things in arrays. One quick fix is simply to remove the object from the array, and for all I know that will remove the drone object from memory, but we should look into this, because if not a better solution should be found.

**Comment by thewrongjames** [comment]
From https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/delete:
> Non-configurable properties cannot be removed. This includes properties of built-in objects like Math, Array, Object and properties that are created as non-configurable with methods like Object.defineProperty().

**Comment by thewrongjames** [comment]
If the items in an array are technically it's properties (which I had always assumed was the case), we will apparently not be able to remove them. However, if they don't, then delete is not the way to remove them, because delete is explicitly for removing properties of objects as, from the same site as above:
> The delete operator removes a given property from an object

**Comment by thewrongjames** [comment]
Additionally, the delete opperator isn't for memory management (from same site):
> Unlike what common belief suggests, the delete operator has nothing to do with directly freeing memory.

I guess it is time I read [the MDN JavaScript Memory Management page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Memory_Management) because according to that we may still need to care about it, even though it is somewhat automatic...

> JavaScript values are allocated when things (objects, strings, etc.) are created and "automatically" freed when they are not used anymore. The latter process is called garbage collection. This "automatically" is a source of confusion and gives JavaScript (and other high-level languages) developers the impression they can decide not to care about memory management. This is a mistake.

**Comment by thewrongjames** [comment]
Okay, I have read the rest of that page, and it doesn't actually suggest any things that developers need to do for memory management, but it does explain two types of automatic 'garbage collection' that the JavaScript interpreter could run to automatically clean up memory that it seems to be suggesting developers should be aware of.

As far as I can tell, just removing the drone from the array should be good enough for both of those automatic methods, so, I shall go ahead and write that up and make a pull request.

**Comment by ennuuos** [comment]
Thanks for doing all that reading.
Could you give an example here of deleting from an array for future reference

**Comment by ennuuos** [comment]
Thanks for doing all that reading.
Due to me NOT doing any reading I just used delete instead of Array.remove().
That is totally and completely my fault.
Thanks for picking up on this.

**Comment by thewrongjames** [comment]
As you have noticed, but just for posterity here, there is no Array.remove(), but there is an [Array.splice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice) method, and that is what will be used in the fix for this.
