### ISSUE TITLE
Test Drones class

### ISSUE THREAD

**Issue by ennuuos** [ennuuos/DronesDoingDroneThingsThreePointOh#3]
The drones class is in dire need of testing

### Tests
- [x] constructor
- [x] .all
- [x] .allConfirmed
- [x] .add
- [x] .remove
- [x] .containsId
- [x] .getDrone
- [x] .ipTemplate

**Comment by thewrongjames** [comment]
To make this more straightforward I have added another issue for working out how to test actually interactions with drones [here](https://github.com/ennuuos/DronesDoingDroneThingsThreePointOh/issues/11), and so I will close this once we have all the non-live tests.

**Comment by thewrongjames** [comment]
I think status and statuses can only really have live tests, so I will remove them from here. They are listed in the other issue.

**Comment by thewrongjames** [comment]
I have added the tests, made sure I hadn't broken anything and merged to master, I will make this as closed.

**Comment by thewrongjames** [comment]
I am reopening this issue due to some re-setting we have done on the branches. Merges to master will now only be done through pull requests, which will close respective issues.
