### ISSUE TITLE
Server does not know when drones disconnect

### ISSUE THREAD

**Issue by ennuuos** [ennuuos/DronesDoingDroneThingsThreePointOh#6]
This could be fixed in multiple ways.

### Ping
Previously we used the ping module to ping the drones each second to check that they are still connected.

### Event Timeout
Another way to do this would be to check if no new navdata has been sent recently, this would imply that the server is no longer connected to a drone.

### Maybe there's a UDP way
I'm not sure about this one, but there might be a way to use the UDP functions to check if the drone is connected currently

**Comment by thewrongjames** [comment]
This was fixed by @ennuuos in 7f699e7ff939b8777d17f9c05640b38385db933f.
