### ISSUE TITLE
Drones do not reconnect

### ISSUE THREAD

**Issue by ennuuos** [ennuuos/DronesDoingDroneThingsThreePointOh#9]
We had this issue in version 2 and fixed it but for some reason the ways I tried fixing it did not work.
For now we can ignore it but it is a good idea to look into what's going on.

**Comment by thewrongjames** [comment]
I have fixed reconnection for cases where the connection is lost but the drone has not lost power on the [drone-connection](https://github.com/ennuuos/DronesDoingDroneThingsThreePointOh/tree/drone-connection) branch. The fix is explained in the commit message [here](https://github.com/ennuuos/DronesDoingDroneThingsThreePointOh/commit/b17c9ad462ea2ab014e669a83681b043cd20ec4d). I am not currently sure why it does not work when the drones loose power. If / when I do get that working, I will merge it to master and close this issue.

**Comment by thewrongjames** [comment]
Okay, I have done some tests and 'learned' a few things...
- Resume isn't needed if connection is just lost to the drone (__almost certain__)
- Resume doesn't seem to allow re-connection after drone restart (__maybe__)
- After restart the drone will accept commands perfectly normally, but will not send navdata, even if the listeners are removed and then re-added (__pretty sure__)
- Second drone objects on the same ip do not work at all, even if the first one is deleted (__almost certain__), I expect special UDP closing stuff is needed (__maybe__)
- And, perhaps most importantly, as far as I can tell, it didn't work in [two](https://github.com/ennuuos/DronesDoingDroneThingsTwoPointOh) (__pretty sure__), and that is not a good sign.

There is more testing to be done, esspecially to confirm the more dubious of these assertions, but I tihnk the only next step from here, if I want I think is correct is correct, is to look into the ar-drone code, and try to work out what changes if the drones restart, and how that is different (from node's perspective) from the drone just loosing and regaining connection.

**Comment by thewrongjames** [comment]
I think I've got it.

Lines 71 to 74 in ar-drone/lib/navdata/UdpNavdataStream.js:
```js
if (navdata.sequenceNumber > this._sequenceNumber) {
  this._sequenceNumber = navdata.sequenceNumber;
  this.emit('data', navdata);
}
```

It only sends navdata if it is newer than the stuff it last recieved. But, if the drone turns off, it seems that it resets it's sequence number counter thingy, and so the ar-drone module thinks it is old. I guess the solution to this is the reset the node-side counter to zero when we loose connection to the drone.

**Comment by thewrongjames** [comment]
Also, with that change, .resume does make a difference now, it sets it up to send demo data again. (It seems that defaults to off).

**Comment by thewrongjames** [comment]
Okay, I have tested my fix, and it works. Drones now reconnect even after they have restarted. As it doesn't seem to have broken anything else and the tests still pass, I have merged to dev and master, and I will close this issue.

**Comment by thewrongjames** [comment]
I am reopening this issue due to some re-setting we have done on the branches. Merges to master will now only be done through pull requests, which will close respective issues.
